---
title: "AM_Tools_Fall2024"
author: "Aiden Maddux"
format: html
editor: visual
---

## Writing assignment 3

I have yet to have any of my work reviewed for publishing. However, I have gone through multiple rounds of editing on my manuscript from a diverse range of committee members and peers. The issue of conflicting edits or edits that are not helpful are very common and something I have struggled with in the past. I currently have the advantage of having a lead PI within the editing process. This allows everyone to be on the same page regarding which edits take first priority. This allows me to only accept edits that my PI would also approve. In the peer review process there is no hierarchy in reviewers which forces the author to take all opinions into account.

When dealing with conflicting reviewers I believe it is up to the author to make the best judgment on which edits to follow. The author will understand his/her project better than anyone else and the small details that it took to form the manuscript. With this added knowledge the author must take into account which edit aligns with their own project the most. If one reviewer is wanting a piece of writing to go in different direction than the project has a whole then I think it is reason

able to ignore this edit. It is also up to the author to defend and justify ignoring and accepting edits. I believe this process actually makes the manuscript better by improving your argument within the paper. If a single reviewer continues to have issues that do not match the other reviewer then I think it is the responsibility of the editor to change the reviewers.

## Writing assignment 4

Predatory journals play a massive role in the dissemination of false or misleading information. Because science and the peer review process has established research as a trustworthy source of information, predatory journals have been able to pass off low quality or false research as credible information by appearing to have the same rigorous peer review process as other journals. This low barrier to publish allows the scientific literature to be flooded with poor or false papers. These papers can have important consequences on public opinion and even policy. On one end of the spectrum are authors who have made mistakes in their research and publish papers in predatory journals out of ignorance. These papers are then read by other and increase the confusion around a topic. This hinders scientific progress and leads to false conclusions. On the other end of the spectrum are authors with malcontent who knowingly create false research or results in order to better their own interests. This creates major division in the public perception of science quality and honesty. Those with aligning beliefs are lead to believe that because a paper was published it must be true. This creates issues in the most back discussions on what is fact or not.

In the fisheries research field I believe predatory journals prey more on authors with sub par research that may have mistakes within them. These paper generally are not meant to make any major claims that would have overreaching impacts on society as a whole. However predatory journals within fisheries do slow down progress by flooding the literature with poor science. These paper are difficult to sift through and require attention to detail when citing papers from different journals.

# Writing assignment 5

The case involving Dr. Andrews and other collaborators would be a very difficult situation for me to navigate. I am sure similar situations happen very often in research studies. If I were one of the collaborators and Dr. Andrews asked to be an author on every single paper that was produced by the collaboration, I would have immediate reservation about adding her. Although the research idea was hers, it sounds like she did not contribute to any of the studies after the initial proposal. To be an author on a paper I believe an individual needs to play an active roll in the research after the initial idea is produced. There are hundreds of steps from the initial idea to the final published paper. I think any small contributions in any of these steps would qualify Dr. Andrews being an author due to it being her idea in the first place.

In my response to Dr. Andrews I would make sure she knew all the work that went into the studies after the initial grant proposal. It would be important for her to see all work that was done without her. I would explain that my grad student and I have put a lot of effort into what we have produced and believe we should be getting the credit. I would then give Dr. Andrews several options that might resolve the situation. Depending on where the study was at in its progression I would offer her the opportunity to make some sort of contribution such as edits, building tables or figures, or general ideas on where the paper should go. I believe this contribution would justify being an author on my paper. I would also offer to name Dr. Andrews very promptly in the acknowledgments and clearly state that the initial idea for the research was hers. I would make sure to be as polite as possible in my response and not escalate the situation.

# Writing assignment 6

Sharing manuscripts to the public before they have been peer reviewed and accepted to a journal has become an increasing common practice among those wishing to further the open science movement. An advantage of this practice is that it gets studies to the public much faster. The peer review process can take months to years to complete. If the paper is of extreme importance to the public an author can share his or her manuscript to the public and make a significant impact quicker. Another advantage of this practice is it increases the transparency of the peer review process. Sharing a paper before it is edited allows the public to see what changes were made to the original manuscript and how the peer review processes works. I believe this increases the public trust in science. A con of this practice is that it circumvents the peer review processes. The peer review process ensures the best science is being shared with the public, by skipping this process the public will see possible bad science.

Personally I do not agree with sharing a manuscript before it has been accepted into a journal. I have a lot of trust in the peer review process and believe it produces better papers for the public. Although there is some loss in transparency in waiting to share the paper I believe the quality of the paper outweighs this concern. I do not think those sharing their manuscript are pushing science in the wrong direction but I personally would not do it.

# Writing assignment 7

Ethical can be a very subjective term depending on the topic and context it is used in. In the context of deciding when a scientific publisher is "ethical" or not there are multiple characteristics to consider that each person may find more or less important. In my opinion an ethical publisher must have two main characteristics. They must be non-profit or minimally profitable and they must care about the quality of science that is being published.

Science in general is built on the mission of providing truth and knowledge to society regardless of individual gain. This is why the open access movement has continued so strongly. I believe people in academia want to share their results with as many people as possible and receive no monetary reward for that science. Why should publishers behave any different? I understand there are costs in distributing science to people and publishers must be able to do this effectively. However after this requirement it met there is no reason publishers should be making extreme profits when the rest of science is built on providing a service for as free as possible.

Publishers also must have adequate peer review processes that maintains a high reputation for quality science. Publishers that want to publish quality science and rigorously filter papers that do not meet this standard are ethical. Publishers are the last line before works are given to the public. They hold a responsibility to share quality science and those with very low standards are not ethical regardless of their publishing prices.

# Writing assignment 8

I would say that this comment reflects the general public's misunderstanding of statistics, study design, and the interpretation of results. What your statistical results "say" is first rooted in your study design and the assumptions of a model or experiment. This already narrows down that you can say about particular topic. The scale, method of data collection, and any unknown variation you cannot account for determines a lot about what you can confidently conclude from your results. Secondly the interpretations of the actual model output requires a lot of knowledge and experience. While these interpretations may seem arbitrary they are rooted in statistical theory. Finally, I would explain that models are our best estimation of truth from an unknown world and they should never be interpreted as absolute truths. Just because a model is saying one thing does not mean it is 100% correct all of the time under every scenario.

# Writing assignment 9

Citizen science could be applied to my research in multiple ways. My work on invasive carp species provides opportunities for the public capture and kill invasive species. I think a citizen science lead study on invasive carp populations could be very useful to determine population demographics in certain systems. Ideally citizens would capture invasive carp and bring these individuals to me to perform measurements on and extract otolith to determine the age of a fish. Capturing invasive carp can be difficult and labor intensive. With limited man power, data on population demographics can be limited. The supplemental data provided by citizens would increase our predictive power of models and lead to better informed management.

Advantages of this study would also include the saving of time and money. There would be no need to pay citizens for capturing carp as it has become a popular sport to bowfish carp in many states. Citizens are already capture carp on their free time and we only have to pick them up. The amount of data that could be collect in this manor would far exceed what traditional techniques could provide with minimal crew members. Disadvantages would include possible loss of some data as some individual fish may be too degraded to take measurements from. This study would also increase the risk of fisherman misidentifying carp species and killing native species. Efforts would have to be made to educate anglers and possiblly prohibit some anglers from giving fish to us.

# Writing assignment 10

As an advisor, I would try to ensure that I was promoting a healthy work environment. This would including starting with myself and making sure that I am not contributing to a toxic work culture. I would try to carry myself professionally and treat others with respect. I would also try my best to police my lab when it comes to unprofessional habitats of any of my student.

Secondly, I would hold communication as a top priority in my lab. I would make sure that I communicated clearly and efficiently to my students the expectations I have for them and for the lab as a whole. I would try to ensure that student felt comfortable communicating to me about their work and personal lives.

Lately, I would do my best to put myself in my students shoes and see things from their perspective. I think this practice is crucial in identifying blind spots in myself and making sure I am not asking anyone to do something I wouldn't do myself. I think this practice allows students to feel like they are not alone and we are working on the project as a team.
